name: Shopify Theme Management

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  manage-theme:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Create and deploy a PR specific Shopify theme when PR is opened/updated
      - name: Deploy PR-specific Shopify theme
        if: github.event.action != 'closed'
        uses: matthew-petrie/shopify-theme-actions@1.2.2
        with:
          ACTION: 'DEPLOYMENT_PREVIEW'
          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
          SHOPIFY_THEME_DIRECTORY: '.' # Or your theme directory
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Remove the previously created PR specific Shopify theme when PR is closed
      - name: Remove PR-specific Shopify theme
        if: github.event.action == 'closed'
        uses: matthew-petrie/shopify-theme-actions@1.2.2
        with:
          ACTION: 'REMOVE_DEPLOYMENT_PREVIEW_THEME'
          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
